package com.nxdmn.xpense.ui

import androidx.annotation.DrawableRes
import com.nxdmn.xpense.R

enum class CategoryIcon(@DrawableRes val resId: Int) {

    ARCADE(R.drawable.moneytree_arcade),
    BANK(R.drawable.moneytree_bank),
    BEAUTY(R.drawable.moneytree_beauty),
    BEER(R.drawable.moneytree_beer),
    BOOK(R.drawable.moneytree_book),
    BULB(R.drawable.moneytree_bulb),
    BUS(R.drawable.moneytree_bus),
    CAFE(R.drawable.moneytree_cafe),
    CALCULATOR(R.drawable.moneytree_calculator),
    CALENDAR(R.drawable.moneytree_calender),
    CAR_SERVICE(R.drawable.moneytree_car_service),
    CASH(R.drawable.moneytree_cash),
    CERTIFICATE(R.drawable.moneytree_certificate),
    CHARITY(R.drawable.moneytree_charity),
    CLOTHING(R.drawable.moneytree_clothing),
    COINS(R.drawable.moneytree_coins),
    COMMENTS(R.drawable.moneytree_comments),
    CONVENIENCE_STORE(R.drawable.moneytree_convenience_store),
    CORPORATE(R.drawable.moneytree_corporate),
    COSMETICS(R.drawable.moneytree_cosmetics),
    DENTIST(R.drawable.moneytree_dentist),
    DOCUMENTS(R.drawable.moneytree_documents),
    EATING(R.drawable.moneytree_eating),
    EDUCATION(R.drawable.moneytree_education),
    ELECTRICITY_BILL(R.drawable.moneytree_electricity_bill),
    ELECTRONICS(R.drawable.moneytree_electronics),
    ENTERTAINMENT(R.drawable.moneytree_entertainment),
    EYE(R.drawable.moneytree_eye),
    FAMILY(R.drawable.moneytree_family),
    FASTFOOD(R.drawable.moneytree_fastfood),
    FINANCIAL_SERVICE(R.drawable.moneytree_financial_services),
    FIRE(R.drawable.moneytree_fire),
    FLIGHT(R.drawable.moneytree_flight),
    FLOWER(R.drawable.moneytree_flower),
    FUEL(R.drawable.moneytree_fuel),
    GAMES(R.drawable.moneytree_games),
    GAS(R.drawable.moneytree_gas),
    GIFT(R.drawable.moneytree_gift),
    GLASSES(R.drawable.moneytree_glasses),
    GROCERIES(R.drawable.moneytree_groceries),
    GYM(R.drawable.moneytree_gym),
    HOLIDAY(R.drawable.moneytree_holiday),
    HOME(R.drawable.moneytree_home),
    HOTEL(R.drawable.moneytree_hotel),
    HOUSEKEEPING(R.drawable.moneytree_housekeeping),
    INTERNET(R.drawable.moneytree_internet),
    INVESTMENTS(R.drawable.moneytree_investments),
    JOB(R.drawable.moneytree_job),
    KARAOKE(R.drawable.moneytree_karaoke),
    KEY(R.drawable.moneytree_key),
    LIFE(R.drawable.moneytree_life),
    LOVE(R.drawable.moneytree_love),
    LUNCH(R.drawable.moneytree_lunch),
    MEDICAL(R.drawable.moneytree_medical),
    MESSAGE(R.drawable.moneytree_message),
    MOVIES(R.drawable.moneytree_movies),
    MUSIC(R.drawable.moneytree_music),
    OTHERS(R.drawable.moneytree_others),
    PACKING(R.drawable.moneytree_packing),
    PAPER(R.drawable.moneytree_paper),
    PARKING(R.drawable.moneytree_parking),
    PETS(R.drawable.moneytree_pets),
    PHARMACY(R.drawable.moneytree_pharmacy),
    PHONE_BILL(R.drawable.moneytree_phone_bill),
    RD(R.drawable.moneytree_rd),
    RENT_CAR(R.drawable.moneytree_rent_car),
    REPAIR(R.drawable.moneytree_repair),
    RESTAURANT(R.drawable.moneytree_restaurant),
    RIBBON(R.drawable.moneytree_ribbon),
    ROAD(R.drawable.moneytree_road),
    SHIPPING(R.drawable.moneytree_shipping),
    SHOES(R.drawable.moneytree_shoes),
    SHOPPING(R.drawable.moneytree_shopping),
    SMOKING(R.drawable.moneytree_smoking),
    SPORTS(R.drawable.moneytree_sports),
    TAXES(R.drawable.moneytree_taxes),
    TAXI(R.drawable.moneytree_taxi),
    TELEVISION(R.drawable.moneytree_television),
    THEATRE(R.drawable.moneytree_theatre),
    TOY(R.drawable.moneytree_toy),
    TRAIN(R.drawable.moneytree_train),
    TRAVEL(R.drawable.moneytree_travel),
    UTILITIES(R.drawable.moneytree_utilities),
    WAREHOUSE(R.drawable.moneytree_warehouse),
    WATER(R.drawable.moneytree_water),
    WATER_BILL(R.drawable.moneytree_water_bill),
    WELFARE(R.drawable.moneytree_welfare);

    companion object {
        @DrawableRes
        fun asRes(stored: Int): Int = entries.first{ it.ordinal == stored}.resId
    }
}